#!/bin/bash
# Run by codespaces after starting

exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -x

mv $HOME/.gitconfig $HOME/.gitconfig.stock
mv $HOME/.zshrc $HOME/.zshrc.stock

sudo apt-get update -y

sudo apt-get -y install stow fish rustc exa htop fzf

brew install neovim lazygit

export PATH=$HOME/.cargo/bin:$PATH

nvim --headless +PlugInstall +qall

# Stow dotfiles
echo 'Stowing dotfiles...'
stow --target=$HOME git tmux vim nvim

#curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
