#!/bin/bash
# Run by codespaces after starting

exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -x

mv $HOME/.gitconfig $HOME/.gitconfig.stock
mv $HOME/.zshrc $HOME/.zshrc.stock

sudo apt-get update -y

sudo apt-get -y install stow fish rustc exa htop

brew install lazygit fzf

# Install neovim
echo 'Installing neovim...'
bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/rolling/utils/installer/install-neovim-from-release)

export PATH=$HOME/.local/bin:$PATH

nvim --headless +PlugInstall +qall

# Install lunarvim
echo 'Installing stable lunarvim...'
no | bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

rm -rf $HOME/.config/lvim
rm $HOME/.local/share/lunarvim/lvim/lua/lvim/core/alpha/dashboard.lua

# Stow dotfiles
echo 'Stowing dotfiles...'
stow --target=$HOME git fish lvim tmux vim

#curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
